kind: pipeline
type: docker
name: default
clone:
  git:
    image: plugins/git
    network_mode: host
    tags: true
steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world2
trigger:
  event:
  - push